/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem.view;


import hospitalmanagementsystem.controller.InpatientController;
import hospitalmanagementsystem.controller.PatientController;
import hospitalmanagementsystem.controller.PatientPaymentController;
import hospitalmanagementsystem.controller.SearchEmployeeController;
import hospitalmanagementsystem.model.Doctor;
import hospitalmanagementsystem.model.InPatient;
import hospitalmanagementsystem.model.Patient;
import hospitalmanagementsystem.model.PatientPayment;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PC
 */
public class SearchEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchEmployee
     */
    public SearchEmployee() {
        initComponents();
        regPatient.setVisible(false);
        dischargep.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        patient = new javax.swing.ButtonGroup();
        patient2 = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabPatient = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        regPatient = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        patient_name = new javax.swing.JTextField();
        patient_dob = new javax.swing.JTextField();
        patient_nic = new javax.swing.JTextField();
        patient_gender = new javax.swing.JTextField();
        patient_tele = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        patient_address = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        patient_id = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        searchNamebtn = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        registerPatient = new javax.swing.JRadioButton();
        newPatient = new javax.swing.JRadioButton();
        update_btn = new javax.swing.JToggleButton();
        cancel_btn = new javax.swing.JToggleButton();
        reset_btn = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        patient_Id = new javax.swing.JTextField();
        p_name = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        statue = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        inpatient = new javax.swing.JRadioButton();
        outpatient = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        dischargep = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dischargedate = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        paymentId = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        d_name = new javax.swing.JLabel();
        d_date = new javax.swing.JLabel();
        s_area = new javax.swing.JLabel();
        d_contact = new javax.swing.JLabel();
        d_email = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        special_area = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        date_d = new javax.swing.JComboBox<>();
        search2 = new javax.swing.JButton();
        cansle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        d_type = new javax.swing.JLabel();
        d_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel18.setText("Telephone No");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPatient.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel6.setBackground(new java.awt.Color(181, 181, 111));

        regPatient.setBackground(new java.awt.Color(214, 236, 193));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel16.setText("Name");

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel17.setText("Date of  Birth");

        jLabel19.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel19.setText("Address");

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel20.setText("NIC");

        jLabel21.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel21.setText("Gender");

        patient_name.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N

        patient_dob.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N
        patient_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_dobActionPerformed(evt);
            }
        });

        patient_nic.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N
        patient_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_nicActionPerformed(evt);
            }
        });

        patient_gender.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N
        patient_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_genderActionPerformed(evt);
            }
        });

        patient_tele.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N
        patient_tele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_teleActionPerformed(evt);
            }
        });

        patient_address.setColumns(20);
        patient_address.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N
        patient_address.setRows(5);
        jScrollPane3.setViewportView(patient_address);

        jLabel22.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel22.setText("Patient Id");

        patient_id.setFont(new java.awt.Font("DinaminaUniWeb", 1, 14)); // NOI18N

        search_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        searchNamebtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        searchNamebtn.setText("Search");
        searchNamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNamebtnActionPerformed(evt);
            }
        });

        jLabel23.setText("jLabel23");

        javax.swing.GroupLayout regPatientLayout = new javax.swing.GroupLayout(regPatient);
        regPatient.setLayout(regPatientLayout);
        regPatientLayout.setHorizontalGroup(
            regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPatientLayout.createSequentialGroup()
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regPatientLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPatientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(85, 85, 85)
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regPatientLayout.createSequentialGroup()
                        .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patient_tele, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patient_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(regPatientLayout.createSequentialGroup()
                        .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regPatientLayout.createSequentialGroup()
                                .addComponent(patient_name, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(searchNamebtn))
                            .addComponent(patient_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(regPatientLayout.createSequentialGroup()
                                .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(search_btn)))
                        .addGap(0, 246, Short.MAX_VALUE))))
        );
        regPatientLayout.setVerticalGroup(
            regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(patient_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNamebtn))
                .addGap(18, 18, 18)
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(patient_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(patient_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(patient_tele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(regPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(38, 38, 38))
        );

        jPanel8.setBackground(new java.awt.Color(122, 195, 122));

        patient2.add(registerPatient);
        registerPatient.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        registerPatient.setText("Registered Patient");
        registerPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPatientActionPerformed(evt);
            }
        });

        patient2.add(newPatient);
        newPatient.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        newPatient.setText("New Patient");
        newPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerPatient)
                .addGap(38, 38, 38)
                .addComponent(newPatient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPatient)
                    .addComponent(newPatient))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        update_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        reset_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        reset_btn.setText("Reset");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(regPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel_btn)
                .addGap(31, 31, 31)
                .addComponent(update_btn)
                .addGap(37, 37, 37)
                .addComponent(reset_btn)
                .addGap(179, 179, 179))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn)
                    .addComponent(update_btn)
                    .addComponent(reset_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPatient.addTab("Patient", jPanel6);

        jPanel2.setBackground(new java.awt.Color(145, 212, 212));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel11.setText("patient id");

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel12.setText("patient Name");

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel13.setText("Payment");

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel14.setText("status ");

        p_name.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N

        payment.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N

        statue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statueActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("SLSCII1134a", 1, 24)); // NOI18N
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        patient.add(inpatient);
        inpatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inpatient.setText("In Patient");
        inpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpatientActionPerformed(evt);
            }
        });

        patient.add(outpatient);
        outpatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        outpatient.setText("Out Patient");
        outpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outpatientActionPerformed(evt);
            }
        });

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        billTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(billTable);

        dischargep.setBackground(new java.awt.Color(145, 212, 212));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel15.setText("Discharge Date");

        dischargedate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout dischargepLayout = new javax.swing.GroupLayout(dischargep);
        dischargep.setLayout(dischargepLayout);
        dischargepLayout.setHorizontalGroup(
            dischargepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dischargepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(dischargedate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        dischargepLayout.setVerticalGroup(
            dischargepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dischargepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dischargepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(dischargedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel24.setText("Paid date");

        jLabel25.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel25.setText("Payment id");

        update.setFont(new java.awt.Font("SLSCII1134a", 1, 24)); // NOI18N
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(inpatient)
                        .addGap(78, 78, 78)
                        .addComponent(outpatient))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(dischargep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addComponent(jLabel25)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel24)))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(patient_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statue, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpatient)
                            .addComponent(outpatient))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(patient_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(paymentId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(statue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(dischargep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );

        tabPatient.addTab("Payments", jPanel2);

        jPanel3.setBackground(new java.awt.Color(165, 237, 142));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Doctor id   :");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText("Doctor Name:");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setText("Available Date :");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setText("Specialist area :");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setText("Contacte number:");

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setText("E-mail:");

        d_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        d_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        s_area.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        d_contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        d_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(198, 243, 152));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Search doctor using date and special area");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Special_area");

        special_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dentist", "Cardiologist", "Neurologist", "Orthopedic Surgeon", "ENT Specialist", "Physiologist" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Date");

        date_d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thurseday", "Friday", "Saturaday" }));
        date_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_dActionPerformed(evt);
            }
        });

        search2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search2.setText("Search");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });

        cansle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cansle.setText("cancle");
        cansle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cansleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(search2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cansle)))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(99, 99, 99)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(date_d, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(special_area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(special_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(date_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search2)
                    .addComponent(cansle))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel10.setText("Doctor type :");

        d_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(doctorTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(d_type, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(489, 489, 489))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(d_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(searchbtn))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(d_email, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(d_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(d_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(s_area, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(d_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(searchbtn)
                            .addComponent(d_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(d_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(d_date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(s_area, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(d_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(d_email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(d_type, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        tabPatient.addTab("Doctor", jPanel3);

        jPanel1.add(tabPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));
        tabPatient.getAccessibleContext().setAccessibleName("Payments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try {
            // TODO add your handling code here:
            //assaign doctor detail to the relevant filed
            Doctor doctor1 =new Doctor();
            int doctorId = Integer.parseInt(d_id.getText());
            doctor1.setEmp_id(doctorId);
            
            ResultSet getDoctorDetails = SearchEmployeeController.getDoctordetails(doctor1);
            
            if(getDoctorDetails.next()){
                d_name.setText(getDoctorDetails.getString("employee_username.emp_name"));
                d_contact.setText(getDoctorDetails.getString("employee_username.emp_contact"));
                d_date.setText(getDoctorDetails.getString("doctor.doctor_schedule"));
                s_area.setText(getDoctorDetails.getString("doctor.specialized_in"));
                d_type.setText(getDoctorDetails.getString("doctor.doctor_type"));
                d_email.setText(getDoctorDetails.getString("employee_username.emp_email"));
            }else{
                JOptionPane.showMessageDialog(null, "there is no employee with this number. ","wrong Pass",JOptionPane.ERROR_MESSAGE);
                d_id.setText("");
                    
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchbtnActionPerformed

    private void date_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_dActionPerformed

    private void cansleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cansleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cansleActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
        tableLoad();
        
    }//GEN-LAST:event_search2ActionPerformed

    private void statueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statueActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(inpatient.isSelected()){
            if(patient_Id.getText().equals("")){
                //error masg
            }
            else{
                int x = JOptionPane.showConfirmDialog(rootPane, "Do you realy want update this ?");
        
                if(x==JOptionPane.YES_OPTION){
        
                try {
                    String pdischarged_date =((JTextField)dischargedate.getDateEditor().getUiComponent()).getText();
                    int patientId = Integer.parseInt(patient_Id.getText());
                    
                    InPatient inpat = new InPatient();
                    
                    inpat.setDate_discharge(pdischarged_date);
                    inpat.setP_id(patientId);
                    
                    int updateP = InpatientController.updateinPatient(inpat);
                    
                    if(updateP>0){
                        //JOptionPane.showMessageDialog(rootPane, "Patient details are updated successfully ! ");
                        
                    }
                    Patient ptn = new Patient();
                    
                    ptn.setP_id(patientId);
                    
                    int payment1 = PatientPaymentController.updateinPatientpayment(ptn);
                    if(payment1>0){
                        JOptionPane.showMessageDialog(rootPane, "Patient details are updated successfully ! ");
                        
                    }
                    else{
                        
                    }
                    
                    
                    
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            }
            
            
        }
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            // TODO add your handling code here:
            if(inpatient.isSelected() || outpatient.isSelected()){
                if(patient_Id.getText().equals("")){
                    JOptionPane.showMessageDialog(rootPane,"Patient Id can not be empty. ","Error",JOptionPane.ERROR_MESSAGE);
            
                }else{
            /*load tabale */
            tableload2();
            int pId = Integer.parseInt(patient_Id.getText());
            
            PatientPayment pPment = new PatientPayment();
            pPment.setP_id(pId);
            
            ResultSet getPayment = PatientPaymentController.getPayment(pPment);
            
            if(getPayment.next()){
                p_name.setText(getPayment.getString("patient.p_name"));
                payment.setText(Integer.toString(getPayment.getInt("payment_patient")));
                statue.setText(getPayment.getString("patientpayment.Patient_paid"));
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"There is no payment record with this patient Id ","wrong Pass",JOptionPane.ERROR_MESSAGE);
            
            }
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Select Patient Type ","wrong Pass",JOptionPane.ERROR_MESSAGE);
            
            }
        } catch (ClassNotFoundException | SQLException ex) {
            //JOptionPane.showMessageDialog(null,"There is no payment record with this patient Id ","wrong Pass",JOptionPane.ERROR_MESSAGE);
            
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void patient_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_nicActionPerformed

    private void patient_teleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_teleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_teleActionPerformed

    private void patient_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_dobActionPerformed

    private void patient_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_genderActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        if(patient_id.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Patient id can not be empty.","Error Message.",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                int P_id = Integer.parseInt(patient_id.getText());
                Patient patient1 = new Patient();
                patient1.setP_id(P_id);
                
                ResultSet setpatient2 = PatientController.getPatient(patient1);
                if(setpatient2.next()){
                    patient_name.setText(setpatient2.getString("p_name"));
                    patient_nic.setText(setpatient2.getString("p_nic"));
                    patient_address.setText(setpatient2.getString("p_address"));
                    patient_dob.setText(setpatient2.getString("p_dob"));
                    patient_tele.setText(setpatient2.getString("p_contacte"));
                    patient_gender.setText(setpatient2.getString("p_gender"));
                    
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Patient id can not be found.","Error Message.",JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
                //JOptionPane.showMessageDialog(rootPane, "Patient id can not be found.","Error Message.",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        
        
        
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        if(patient_id.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Patient id can not be empty.","Error Message.",JOptionPane.ERROR_MESSAGE);

        }else{
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you realy want to update this ?");
        if(x==JOptionPane.YES_OPTION){
                try {
                    int p_id = Integer.parseInt(patient_id.getText());
                    String pname = patient_name.getText();
                    String pAddress = patient_address.getText();
                    String pgender =patient_gender.getText();
                    String pnic = patient_nic.getText();
                    String ptel = patient_tele.getText();
                    
                    Patient patient1 = new Patient(p_id, pname, pgender, pnic, ptel, pnic, pAddress);
                    int updatepatient = PatientController.updatePatient(patient1);
                    if(updatepatient>0){
                        JOptionPane.showMessageDialog(rootPane, "Patient details updated successfully.");
                        patient_id.setText("");
                        patient_address.setText("");
                        patient_dob.setText("");
                        patient_gender.setText("");
                        patient_name.setText("");
                        patient_tele.setText("");
                        patient_nic.setText("");
                    }       } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
        }
        }
        
        
        
        
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void searchNamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNamebtnActionPerformed
        // TODO add your handling code here:
        if(patient_name.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Patient name can not be empty.","Error Message.",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                //int P_id = Integer.parseInt(patient_id.getText());
                String pname = patient_name.getText();
                Patient patient1 = new Patient();
                //patient1.setP_id(P_id);
                patient1.setName(pname);
                
                
                
                ResultSet setpatient2 = PatientController.getPatient(patient1);
                if(setpatient2.next()){
                    patient_id.setText(Integer.toString(setpatient2.getInt("p_id")));
                    patient_nic.setText(setpatient2.getString("p_nic"));
                    patient_address.setText(setpatient2.getString("p_address"));
                    patient_dob.setText(setpatient2.getString("p_dob"));
                    patient_tele.setText(setpatient2.getString("p_contacte"));
                    patient_gender.setText(setpatient2.getString("p_gender"));
                    
                }
            } catch (ClassNotFoundException | SQLException ex) {
                //Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Patient can not be found.","Error Message.",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_searchNamebtnActionPerformed

    private void registerPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPatientActionPerformed
        // TODO add your handling code here:
        regPatient.setVisible(true);
    }//GEN-LAST:event_registerPatientActionPerformed

    private void newPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PatientRegistration pr = new PatientRegistration();
        pr.setVisible(true);
    }//GEN-LAST:event_newPatientActionPerformed

    private void inpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpatientActionPerformed
        // TODO add your handling code here:
        dischargep.setVisible(true);
    }//GEN-LAST:event_inpatientActionPerformed

    private void outpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outpatientActionPerformed
        // TODO add your handling code here:
        dischargep.setVisible(false);
    }//GEN-LAST:event_outpatientActionPerformed

    private void billTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTableMouseClicked
        // TODO add your handling code here:
        int r = billTable.getSelectedRow();
        String payment_id = billTable.getValueAt(r, 0).toString();
        String payment1 = billTable.getValueAt(r, 3).toString();
        
        paymentId.setText(payment_id);
        payment.setText(payment1);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_billTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billTable;
    private javax.swing.JToggleButton cancel_btn;
    private javax.swing.JButton cansle;
    private javax.swing.JLabel d_contact;
    private javax.swing.JLabel d_date;
    private javax.swing.JLabel d_email;
    private javax.swing.JTextField d_id;
    private javax.swing.JLabel d_name;
    private javax.swing.JLabel d_type;
    private javax.swing.JComboBox<String> date_d;
    private com.toedter.calendar.JDateChooser dischargedate;
    private javax.swing.JPanel dischargep;
    private javax.swing.JTable doctorTable;
    private javax.swing.JRadioButton inpatient;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton newPatient;
    private javax.swing.JRadioButton outpatient;
    private javax.swing.JLabel p_name;
    private javax.swing.ButtonGroup patient;
    private javax.swing.ButtonGroup patient2;
    private javax.swing.JTextField patient_Id;
    private javax.swing.JTextArea patient_address;
    private javax.swing.JTextField patient_dob;
    private javax.swing.JTextField patient_gender;
    private javax.swing.JTextField patient_id;
    private javax.swing.JTextField patient_name;
    private javax.swing.JTextField patient_nic;
    private javax.swing.JTextField patient_tele;
    private javax.swing.JLabel payment;
    private javax.swing.JLabel paymentId;
    private javax.swing.JPanel regPatient;
    private javax.swing.JRadioButton registerPatient;
    private javax.swing.JToggleButton reset_btn;
    private javax.swing.JLabel s_area;
    private javax.swing.JButton search;
    private javax.swing.JButton search2;
    private javax.swing.JToggleButton searchNamebtn;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JComboBox<String> special_area;
    private javax.swing.JTextField statue;
    private javax.swing.JTabbedPane tabPatient;
    private javax.swing.JButton update;
    private javax.swing.JToggleButton update_btn;
    // End of variables declaration//GEN-END:variables

       public void tableLoad() {
        
        try {
            Doctor doctor = new Doctor();
            String date = date_d.getSelectedItem().toString();
            String specialIn = special_area.getSelectedItem().toString();
            
            doctor.setSchedule(date);
            doctor.setSpecialized_in(specialIn);
            
            ResultSet getDoctorDetailsdate = SearchEmployeeController.getDoctordetailsDate(doctor);
            doctorTable.setModel(DbUtils.resultSetToTableModel(getDoctorDetailsdate));
                
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PatientReportUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
      
           
       }
       //load patient bill
       public void tableload2(){
        try {
            int pId = Integer.parseInt(patient_Id.getText());
            PatientPayment ppayment = new PatientPayment();
            ppayment.setP_id(pId);
            ResultSet getpayment = PatientPaymentController.getPaymentbill(ppayment);
            billTable.setModel(DbUtils.resultSetToTableModel(getpayment));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
       }


}

























